### ISSUE TITLE
Error for too small of a solid angle

### ISSUE THREAD

**Issue by mtpenny** [synthpop-galaxy/synthpop#4]
Using a solid angle of 5e-7 deg^2 results in an error, when it should probably be a warning. Here is the relevant error message:

Default unit for solid_angle was changed to square Degree!
	solid_angle = 5.000e-07 seems to be to small for square degree
	You might want to use (1.641e-03) square degree
	or set 'solid_angle_unit' to 'sr'. 
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py39/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/py39/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/penny/synthpop/synthpop/__main__.py", line 10, in <module>
    main()
  File "/Users/penny/synthpop/synthpop/synthpop_main.py", line 617, in main
    mod.process_all()
  File "/Users/penny/synthpop/synthpop/synthpop_main.py", line 592, in process_all
    self.process_location(*l_b_deg, solid_angle=self.parms.solid_angle,
  File "/Users/penny/synthpop/synthpop/synthpop_main.py", line 547, in process_location
    self.update_location(l_deg=l_deg, b_deg=b_deg,
  File "/Users/penny/synthpop/synthpop/synthpop_main.py", line 237, in update_location
    raise ValueError(msg)
ValueError: Default unit for solid_angle was changed to square Degree!
	solid_angle = 5.000e-07 seems to be to small for square degree
	You might want to use (1.641e-03) square degree
	or set 'solid_angle_unit' to 'sr'.

**Comment by hustonm** [comment]
Can you confirm whether this happens in the dev version? I thought I removed it because I ran into a similar issue.

**Comment by hustonm** [comment]
@mtpenny is this still a problem? I will close the issue if not

**Comment by mtpenny** [comment]
This doesn't seem to be a problem now - I'll close it. Thanks Macy!
